openapi: 3.0.1
info:
  title: MelodyMate ChatGPT Plugin
  description: A ChatGPT plugin for making playlists on Spotify.
  version: 'v1'
servers:
  - url: https://melody-mate.vercel.co
paths:
  /playlist:
    get:
      operationId: fetchPlaylist
      summary: Fetch a playlist based on a query
      parameters:
        - name: query
          in: query
          description: The query to search for in playlists
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fetchPlaylistResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  schemas:
    fetchPlaylistResponse:
      type: object
      properties:
        message:
          type: string
          description: A message indicating the status of the playlist creation
        playlist_url:
          type: string
          description: The URL of the created playlist on Spotify
    errorResponse:
      type: object
      properties:
        error:
          type: string
          description: An error message describing the issue
